name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev libffi-dev
          pip install --upgrade buildozer Cython==0.29.33

      - name: Accept Android Licenses & Build APK
        run: |
          buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy/g' buildozer.spec
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: starrdrop-apk
          path: bin/*.apk
          
